version: '3.2'

services:
  postgresql:
    image: postgres
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    user: "$UID:$GID"
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
volumes:
 data: {}
 schema.sql: {}
 grafana: {}
